mdapipkg/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApp__c/JobApp__c.object-meta.xml
<CustomObject>
    <description>Candidate-Position junction</description>
    <label>JobApp</label>
    <nameField>
        <displayFormat>JA-{MM}-{YYYY}-{0}</displayFormat>
        <label>JobApp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApp__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>JobApps</relationshipLabel>
    <relationshipName>JobApps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mdapipkg/objects/JobApp__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Position closed</errorMessage>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Opened</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>JobApps</relationshipLabel>
    <relationshipName>JobApps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mdapipkg/objects/JobApp__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Resume link</description>
    <inlineHelpText>Resume URL</inlineHelpText>
    <label>Resume</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

mdapipkg/objects/JobApp__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st New stage</fullName>
            </value>
            <value>
                <fullName>2nd Resume accepted</fullName>
            </value>
            <value>
                <fullName>2nd Resume rejected</fullName>
            </value>
            <value>
                <fullName>3rd Personal interview successfully passed</fullName>
            </value>
            <value>
                <fullName>3rd Personal interview failed</fullName>
            </value>
            <value>
                <fullName>4th Technical interview successfully passed</fullName>
            </value>
            <value>
                <fullName>4th Technical interview failed</fullName>
            </value>
            <value>
                <fullName>5th English interview successfully passed</fullName>
            </value>
            <value>
                <fullName>5th English interview failed</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapipkg/classes/JobAppHelperTest.cls
@isTest
private class JobAppHelperTest {
    @TestSetup
    static void makeData(){
        RecruitingTestUtils.createOpenedPositions(1);
        RecruitingTestUtils.createCandidates(1);
    }

    @isTest
    static void getJobAppsTest() {
        List<Position__c> position = [SELECT Id FROM Position__c];
        List<Candidate__c> candidade = [SELECT Id FROM Candidate__c];
        JobApp__c jobApp = new JobApp__c();
        jobApp.Stage__c = RecruitingTestUtils.FIRST_STAGE;
        jobApp.Resume__c = RecruitingTestUtils.TEST_URL;
        jobApp.Candidate__c = candidade[0].Id;
        jobApp.Position__c = position[0].Id;
        insert jobApp;
        Test.startTest();
        List<JobApp__c> jobApps = JobAppHelper.getJobApps(position[0].Id);
        Test.stopTest();
        System.assertEquals(1, jobApps.size());
    }

}