force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapipkg/objects/Position__c/fields/Date_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed__c</fullName>
    <label>Date Closed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Tests/PositionsAutoCloseOldTest.cls
@isTest
private class PositionsAutoCloseOldTest {
    @TestSetup
    static void makeData(){
        Date dateOpened = Date.today() - RecruitingTestUtils.DAYS_EXPIRED;
        RecruitingTestUtils.createOpenedPositions(5000, dateOpened);
        RecruitingTestUtils.createOpenedPositions(5);
    }
    @isTest
    static void positionsAutoCloseOldTest() {
        Test.startTest();
        String jobId = System.schedule(RecruitingTestUtils.CLOSE_OLD_POSITIONS_TEST,
        PositionsAutoCloseOld.EVERY_DAY, new PositionsAutoCloseOld());
        CronTrigger ct = [SELECT NextFireTime FROM CronTrigger WHERE id = :jobId];
        Test.stopTest();
        DateTime dt = DateTime.newInstance(Date.today() + 1, Time.newInstance(0, 0, 0, 0));
        System.assertEquals(dt, ct.NextFireTime);
        List<Position__c> closedPositions = [SELECT Date_Closed__c FROM Position__c WHERE 
                                        Status__c =: PositionsAutoCloseOldHandler.CLOSED];
        Integer openedPositionsCount = [SELECT COUNT() FROM Position__c WHERE 
                                        Status__c =: PositionsAutoCloseOldHandler.OPENED];
        Boolean isAllDatesCorrect = true;
        for (Position__c position : closedPositions) {
            if (position.Date_Closed__c != Date.today()) {
                isAllDatesCorrect = false;
            }
        }
        System.assertEquals(5000, closedPositions.size());
        System.assertEquals(5, openedPositionsCount);
        System.assert(isAllDatesCorrect);
    }
}