force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapipkg/objects/Position__c/fields/Date_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed__c</fullName>
    <label>Date Closed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Main/PositionTriggerHandler.cls
public without sharing class PositionTriggerHandler {
    public void setDateClosed(List<Position__c> newPositions, List<Position__c> oldPositions) {
        for (Integer i = 0; i < newPositions.size(); i++) {
            if (newPositions[i].Status__c == PositionsHelper.CLOSED && 
                oldPositions[i].Status__c != PositionsHelper.CLOSED &&
                newPositions[i].Date_Closed__c != Date.today()) {
                    newPositions[i].Date_Closed__c = Date.today();
            }

        }
    }
}