force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapipkg/objects/Position__c/fields/Date_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed__c</fullName>
    <label>Date Closed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Tests/PositionTriggerTest.cls
@isTest
private  class PositionTriggerTest {
    @TestSetup
    static void makeData(){
        RecruitingTestUtils.createOpenedPositions(201);
    }
    @isTest
    static void setDateClosedTest() {
        Boolean isAllDatesCorrect = true;
        List<Position__c> positions = [SELECT Status__c FROM Position__c WHERE Status__c =:RecruitingTestUtils.OPENED];
        for (Position__c position : positions) {
            position.Status__c = RecruitingTestUtils.CLOSED;
        }
        Test.startTest();
        PositionsHelper.updatePositions(positions);
        Test.stopTest();
        positions = [SELECT Date_Closed__c FROM Position__c WHERE Status__c =:RecruitingTestUtils.CLOSED];
        for (Position__c position : positions) {
            if (position.Date_Closed__c != Date.today()) {
                isAllDatesCorrect = false;
            }
        }
        System.assert(isAllDatesCorrect);
    }
}