force-app/main/default/objects/JobApp__c/JobApp__c.object-meta.xml
<CustomObject>
    <description>Candidate-Position junction</description>
    <label>JobApp</label>
    <nameField>
        <displayFormat>JA-{MM}-{YYYY}-{0}</displayFormat>
        <label>JobApp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapipkg/objects/JobApp__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Position closed</errorMessage>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Opened</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>JobApps</relationshipLabel>
    <relationshipName>JobApps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mdapipkg/objects/JobApp__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st New stage</fullName>
            </value>
            <value>
                <fullName>2nd Resume accepted</fullName>
            </value>
            <value>
                <fullName>2nd Resume rejected</fullName>
            </value>
            <value>
                <fullName>3rd Personal interview successfully passed</fullName>
            </value>
            <value>
                <fullName>3rd Personal interview failed</fullName>
            </value>
            <value>
                <fullName>4th Technical interview successfully passed</fullName>
            </value>
            <value>
                <fullName>4th Technical interview failed</fullName>
            </value>
            <value>
                <fullName>5th English interview successfully passed</fullName>
            </value>
            <value>
                <fullName>5th English interview failed</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapipkg/classes/JobAppTriggerHandler.cls
public without sharing class JobAppTriggerHandler {
    public void closePositions(List<JobApp__c> newJobApps, List<JobApp__c> oldJobApps) {
        Set<Id> positionsIds = new Set<Id>();
        for (Integer i = 0; i < newJobApps.size(); i++) {
            if (newJobApps[i].Stage__c == PositionsHelper.HIRED && 
                oldJobApps[i].Stage__c != PositionsHelper.HIRED) {
                    positionsIds.add(newJobApps[i].Position__c);
            }
        }
        
        List<Position__c> positions = [SELECT Id, Name, Status__c FROM Position__c 
                                        WHERE (Id IN : positionsIds AND Status__c =: PositionsHelper.OPENED)];
        for (Position__c position : positions) {
                position.Status__c = PositionsHelper.CLOSED;
        }
        update positions;
    }
}